project:
  type: website
  output-dir: docs 
website:
  title: "Portfolio"
  site-url: "https://IngramLT.github.io/Portfolio/"
  repo-url: "https://github.com/IngramLT/Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



